
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Return the current persisted settings.
 */
async getAppSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("get_app_settings");
},
/**
 * Return the hard-coded default settings (used to reset / seed the UI).
 */
async getDefaultSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("get_default_settings");
},
/**
 * Validate + persist + emit a new paste delay.
 */
async changePasteDelayMs(pasteDelayMs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_delay_ms", { pasteDelayMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the overlay-enabled toggle.
 */
async changeOverlayEnabled(overlayEnabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_enabled", { overlayEnabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the trigger-mode-enabled toggle.
 */
async changeTriggerModeEnabled(triggerModeEnabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_trigger_mode_enabled", { triggerModeEnabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the hold/tap threshold.
 */
async changeHoldTapThresholdMs(holdTapThresholdMs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_hold_tap_threshold_ms", { holdTapThresholdMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the selected microphone device.
 */
async setSelectedMicrophone(selectedMicrophone: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_microphone", { selectedMicrophone }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the selected output device.
 */
async setSelectedOutputDevice(selectedOutputDevice: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_output_device", { selectedOutputDevice }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the audio-feedback toggle.
 */
async changeAudioFeedback(audioFeedback: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback", { audioFeedback }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the audio-feedback volume.
 */
async changeAudioFeedbackVolume(audioFeedbackVolume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_volume", { audioFeedbackVolume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the mute-while-recording toggle.
 */
async changeMuteWhileRecording(muteWhileRecording: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mute_while_recording", { muteWhileRecording }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the selected model.
 */
async changeSelectedModel(selectedModel: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_selected_model", { selectedModel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the selected language.
 */
async changeSelectedLanguage(selectedLanguage: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_selected_language", { selectedLanguage }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the translate-to-english toggle.
 */
async changeTranslateToEnglish(translateToEnglish: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translate_to_english", { translateToEnglish }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the model-unload timeout.
 */
async changeModelUnloadTimeout(modelUnloadTimeout: ModelUnloadTimeout) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_model_unload_timeout", { modelUnloadTimeout }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the auto-submit toggle.
 */
async changeAutoSubmit(autoSubmit: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit", { autoSubmit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the auto-submit key.
 */
async changeAutoSubmitKey(autoSubmitKey: AutoSubmitKey) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_key", { autoSubmitKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the append-trailing-space toggle.
 */
async changeAppendTrailingSpace(appendTrailingSpace: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_append_trailing_space", { appendTrailingSpace }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the start-hidden toggle.
 */
async changeStartHidden(startHidden: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_start_hidden", { startHidden }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the autostart-enabled toggle.
 */
async changeAutostartEnabled(autostartEnabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_autostart_enabled", { autostartEnabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the show-tray-icon toggle.
 */
async changeShowTrayIcon(showTrayIcon: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_tray_icon", { showTrayIcon }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Show (and focus) the main settings window, restoring the Dock icon on macOS.
 */
async showMainWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application settings persisted via `tauri-plugin-store` to
 * `settings_store.json` under the single `"settings"` key.
 * 
 * Every field carries a `#[serde(default = "...")]` so that settings written
 * by an older build (missing newer fields) still deserialize cleanly.
 */
export type AppSettings = { trigger_mode_enabled?: boolean; hold_tap_threshold_ms?: number; selected_microphone?: string | null; selected_output_device?: string | null; audio_feedback?: boolean; audio_feedback_volume?: number; mute_while_recording?: boolean; selected_model?: string | null; selected_language?: string; translate_to_english?: boolean; model_unload_timeout?: ModelUnloadTimeout; paste_delay_ms?: number; auto_submit?: boolean; auto_submit_key?: AutoSubmitKey; append_trailing_space?: boolean; overlay_enabled?: boolean; start_hidden?: boolean; autostart_enabled?: boolean; show_tray_icon?: boolean }
export type AutoSubmitKey = "enter" | "ctrl_enter" | "cmd_enter"
export type ModelUnloadTimeout = "never" | "immediately" | { seconds: number } | { minutes: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
