
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Return the current persisted settings.
 */
async getAppSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("get_app_settings");
},
/**
 * Return the hard-coded default settings (used to reset / seed the UI).
 */
async getDefaultSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("get_default_settings");
},
/**
 * Validate + persist + emit a new paste delay.
 */
async changePasteDelayMs(pasteDelayMs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_delay_ms", { pasteDelayMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the overlay-enabled toggle.
 */
async changeOverlayEnabled(overlayEnabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_enabled", { overlayEnabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the trigger-mode-enabled toggle.
 */
async changeTriggerModeEnabled(triggerModeEnabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_trigger_mode_enabled", { triggerModeEnabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the hold/tap threshold.
 */
async changeHoldTapThresholdMs(holdTapThresholdMs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_hold_tap_threshold_ms", { holdTapThresholdMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the selected microphone device.
 */
async setSelectedMicrophone(selectedMicrophone: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_microphone", { selectedMicrophone }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the selected output device.
 */
async setSelectedOutputDevice(selectedOutputDevice: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_output_device", { selectedOutputDevice }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the audio-feedback toggle.
 */
async changeAudioFeedback(audioFeedback: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback", { audioFeedback }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the audio-feedback volume.
 */
async changeAudioFeedbackVolume(audioFeedbackVolume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_volume", { audioFeedbackVolume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the mute-while-recording toggle.
 */
async changeMuteWhileRecording(muteWhileRecording: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mute_while_recording", { muteWhileRecording }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the selected model.
 */
async changeSelectedModel(selectedModel: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_selected_model", { selectedModel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the selected language.
 */
async changeSelectedLanguage(selectedLanguage: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_selected_language", { selectedLanguage }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the translate-to-english toggle.
 */
async changeTranslateToEnglish(translateToEnglish: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translate_to_english", { translateToEnglish }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the model-unload timeout.
 */
async changeModelUnloadTimeout(modelUnloadTimeout: ModelUnloadTimeout) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_model_unload_timeout", { modelUnloadTimeout }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the auto-submit toggle.
 */
async changeAutoSubmit(autoSubmit: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit", { autoSubmit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the auto-submit key.
 */
async changeAutoSubmitKey(autoSubmitKey: AutoSubmitKey) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_key", { autoSubmitKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the append-trailing-space toggle.
 */
async changeAppendTrailingSpace(appendTrailingSpace: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_append_trailing_space", { appendTrailingSpace }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the start-hidden toggle.
 */
async changeStartHidden(startHidden: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_start_hidden", { startHidden }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the autostart-enabled toggle, then reconcile the
 * OS-level launch-agent registration to match.
 * 
 * Persistence always happens first. The autostart plugin call is best-effort:
 * if the OS rejects enabling/disabling the launch agent we log the error but
 * do NOT fail the command, so the user's saved preference still sticks.
 */
async changeAutostartEnabled(autostartEnabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_autostart_enabled", { autostartEnabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate + persist + emit the show-tray-icon toggle.
 */
async changeShowTrayIcon(showTrayIcon: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_tray_icon", { showTrayIcon }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Show (and focus) the main settings window, restoring the Dock icon on macOS.
 */
async showMainWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detect the macOS "Press 🌐 to…" setting so the frontend can show a one-time
 * nudge when Fn won't work as a push-to-talk trigger.
 * 
 * macOS stores this as `AppleFnUsageType` in the `com.apple.HIToolbox` defaults
 * domain. `0` means "Do Nothing" (the value Stenographer needs); any non-zero
 * value (Change Input Source, Show Emoji & Symbols, Start Dictation, …) will
 * intercept the Fn key before our CGEventTap sees it.
 * 
 * Resilience: if the key is missing or unparseable we return `ok: true,
 * current: -1` so the app does not nag users whose setup we can't read.
 * Non-macOS always returns `ok: true`.
 */
async checkFnKeyBehavior() : Promise<FnKeyBehavior> {
    return await TAURI_INVOKE("check_fn_key_behavior");
},
/**
 * List available input (microphone) devices.
 */
async getAvailableMicrophones() : Promise<DeviceInfo[]> {
    return await TAURI_INVOKE("get_available_microphones");
},
/**
 * List available output (speaker) devices.
 */
async getAvailableOutputDevices() : Promise<DeviceInfo[]> {
    return await TAURI_INVOKE("get_available_output_devices");
},
/**
 * Whether a recording is currently in progress.
 */
async isRecording() : Promise<boolean> {
    return await TAURI_INVOKE("is_recording");
},
/**
 * Play the start feedback sound so the user can preview volume / output device.
 */
async playTestSound() : Promise<void> {
    await TAURI_INVOKE("play_test_sound");
},
/**
 * Initialize the global Enigo instance (must run on the main thread). Fails if
 * Accessibility permission has not been granted. Idempotent.
 */
async initializeEnigo() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_enigo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start the Fn-key listener and store its handle in managed state. Fails if
 * Accessibility permission has not been granted (the CGEventTap can't install).
 * Idempotent: a no-op if the listener is already running.
 */
async initializeShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel any in-flight recording/transcription by submitting `Cancel` to the
 * coordinator.
 */
async cancelOperation() : Promise<void> {
    await TAURI_INVOKE("cancel_operation");
},
/**
 * Full catalog with `is_downloaded` / `is_downloading` reflecting disk state.
 */
async getAvailableModels() : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stream a model download. Emits `model-download-progress` while running and
 * `model-download-complete` / `model-download-failed` on settle.
 */
async downloadModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Request cancellation of an in-flight download. The partial file is kept for
 * later resume. Emits `model-download-cancelled`.
 */
async cancelDownload(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a downloaded model. If it's the active model, unload it and clear the
 * persisted selection first.
 */
async deleteModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the active model and eagerly load it (unless the unload timeout is
 * `Immediately`, in which case it loads on the next transcription).
 */
async setActiveModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The persisted active model id (empty string when none selected).
 */
async getCurrentModel() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether a model load is currently in progress (no model loaded yet).
 */
async isModelLoading() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_model_loading") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist a new model-unload timeout (idle watcher picks it up next tick).
 */
async setModelUnloadTimeout(timeout: ModelUnloadTimeout) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_model_unload_timeout", { timeout }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Manually unload the loaded model (frees memory until next transcription).
 */
async unloadModelManually() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unload_model_manually") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether the app currently has macOS Accessibility (AX) permission.
 * 
 * Required for the global Fn key listener and synthetic keystroke injection.
 * Pure check — does NOT prompt the user.
 */
async checkAccessibilityPermission() : Promise<boolean> {
    return await TAURI_INVOKE("check_accessibility_permission");
},
/**
 * Request macOS Accessibility permission.
 * 
 * On macOS this triggers the system "grant Accessibility" prompt and opens the
 * relevant System Settings pane. The grant is asynchronous and user-driven, so
 * callers should poll [`check_accessibility_permission`] afterwards rather than
 * assume success on return.
 */
async requestAccessibilityPermission() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_accessibility_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether the app currently has macOS Microphone permission.
 * 
 * Pure check — does NOT prompt the user.
 */
async checkMicrophonePermission() : Promise<boolean> {
    return await TAURI_INVOKE("check_microphone_permission");
},
/**
 * Request macOS Microphone permission.
 * 
 * On macOS this calls `AVCaptureDevice requestAccessForMediaType`, which shows
 * the system microphone prompt the first time it is called for this app. The
 * result is delivered asynchronously to the user, so callers should poll
 * [`check_microphone_permission`] afterwards rather than assume success on
 * return.
 */
async requestMicrophonePermission() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_microphone_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application settings persisted via `tauri-plugin-store` to
 * `settings_store.json` under the single `"settings"` key.
 * 
 * Every field carries a `#[serde(default = "...")]` so that settings written
 * by an older build (missing newer fields) still deserialize cleanly.
 */
export type AppSettings = { trigger_mode_enabled?: boolean; hold_tap_threshold_ms?: number; selected_microphone?: string | null; selected_output_device?: string | null; audio_feedback?: boolean; audio_feedback_volume?: number; mute_while_recording?: boolean; selected_model?: string | null; selected_language?: string; translate_to_english?: boolean; model_unload_timeout?: ModelUnloadTimeout; paste_delay_ms?: number; auto_submit?: boolean; auto_submit_key?: AutoSubmitKey; append_trailing_space?: boolean; overlay_enabled?: boolean; start_hidden?: boolean; autostart_enabled?: boolean; show_tray_icon?: boolean }
export type AutoSubmitKey = "enter" | "ctrl_enter" | "cmd_enter"
/**
 * Device descriptor returned to the frontend.
 */
export type DeviceInfo = { name: string; is_default: boolean }
export type EngineType = "Whisper" | "Parakeet"
/**
 * Result of inspecting the macOS "Press 🌐 to…" (Globe/Fn key) behavior.
 * 
 * `ok` is `true` when Fn is safe to use as a push-to-talk trigger — i.e. the
 * system setting is "Do Nothing" (`current == 0`) OR the key could not be read
 * (we fail open so the UI never nags wrongly). `current` is the raw
 * `AppleFnUsageType` value (`0` = Do Nothing, `1` = Change Input Source,
 * `2` = Show Emoji & Symbols on older macOS, `3` = Show Emoji & Symbols /
 * "Start Dictation"-style behaviors on newer macOS, etc.); `-1` means the key
 * was absent or unreadable.
 */
export type FnKeyBehavior = { 
/**
 * `true` if Fn is safe to use for push-to-talk (setting is "Do Nothing" or unknown).
 */
ok: boolean; 
/**
 * Raw `AppleFnUsageType` value; `-1` if absent/unreadable.
 */
current: number }
export type ModelInfo = { id: string; name: string; description: string; filename: string; url: string | null; sha256: string | null; size_mb: number; is_downloaded: boolean; is_downloading: boolean; partial_size: number; is_directory: boolean; engine_type: EngineType; 
/**
 * 0.0 to 1.0, higher is more accurate
 */
accuracy_score: number; 
/**
 * 0.0 to 1.0, higher is faster
 */
speed_score: number; 
/**
 * Whether the model supports translating to English
 */
supports_translation: boolean; 
/**
 * Whether this is the recommended model for new users
 */
is_recommended: boolean; 
/**
 * Languages this model can transcribe (BCP-47 codes)
 */
supported_languages: string[]; 
/**
 * Whether the user can explicitly pick a language
 */
supports_language_selection: boolean }
export type ModelUnloadTimeout = "never" | "immediately" | { seconds: number } | { minutes: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
